language: cpp
os: linux
dist: xenial
jobs:
  include:
    - name: "Xenial Linux"
      os: linux
      cache: ccache
      compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build
      env:
       - GENERATOR=Ninja
       - MKL_INCLUDE_PATH=/opt/intel/mkl/include
       - MKL_LIBRARY_PATH=/opt/intel/mkl/lib/intel64
      before_script:
        # See https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo for details
        - curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | sudo apt-key add -
        - echo "deb https://apt.repos.intel.com/mkl all main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get -qq update
        - sudo apt-get -y install intel-mkl-64bit-2020.0-088
    - name: "MacOS"
      os: osx
      cache:
        directories:
          - $HOME/.ccache
      osx_image: xcode10.2 # macOS 14 required for 2020.1.216 MKL
      compiler: clang
      env:
        - GENERATOR=Ninja
        - MKL_VERSION=2020.1.216
        - MKL_NAME=m_mkl_$MKL_VERSION
        - MKL_INCLUDE_PATH=/opt/intel/mkl/include
        - MKL_LIBRARY_PATH=/opt/intel/compilers_and_libraries_$MKL_VERSION/mac/mkl/lib
      before_install:
        - brew install ninja ccache
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
        - curl http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16525/$MKL_NAME.dmg --output $MKL_NAME.dmg
        - sudo hdiutil attach $MKL_NAME.dmg
        - sed 's/=decline/=accept/g' $(find /Volumes/$MKL_NAME -name "silent.cfg" -print) > ~/silent.cfg
        - sudo $(find /Volumes/$MKL_NAME -name "install.sh" -print) --silent ~/silent.cfg
        - sudo hdiutil detach /Volumes/$MKL_NAME
    - name: "Windows"
      os: windows
      cache:
        directories:
          - $LOCALAPPDATA/Mozilla/sccache
      env:
       - GENERATOR="Visual Studio 14 2015 Win64"  # VS2015 required OpenCV 3.2
       - MKL_VERSION=2020.1.216
       - MKL_NAME=intelmkl.static.win-x64
       - MKL_INCLUDE_PATH=C:/Users/travis/.nuget/packages/$MKL_NAME/$MKL_VERSION/lib/native/include
       - MKL_LIBRARY_PATH=C:/Users/travis/.nuget/packages/$MKL_NAME/$MKL_VERSION/lib/native/win-x64
      before_install:
        # https://chocolatey.org/packages/Paket
        # microsoft-visual-cpp-build-tools for Visual Studio 2015
        - choco install paket microsoft-visual-cpp-build-tools sccache
        - paket init
        # https://www.nuget.org/packages/intelmkl.static.win-x64/
        - paket add $MKL_NAME --version $MKL_VERSION

script:
  - mkdir build_dir
  - cmake -G "$GENERATOR" -Bbuild_dir -Hmeta_build -DCMAKE_BUILD_TYPE=Release -DBUILD_GUI=False
  - cmake --build build_dir --config Release
