set(EP_REQUIRED_PROJECTS Eigen GLog GFlags Ceres OpenCV Sophus tinyxml2)
set(EP_URL "https://github.com/dmirota/Calibu.git")


#set(EP_PATCH "${CMAKE_CURRENT_LIST_DIR}/${EP_NAME}.patch")

cma_end_definition()

set(EP_CMAKE_ARGS
  -DCMAKE_USER_MAKE_RULES_OVERRIDE:FILEPATH=${CMAKE_USER_MAKE_RULES_OVERRIDE}
  -DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX:FILEPATH=${CMAKE_USER_MAKE_RULES_OVERRIDE_CXX}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  "-DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS} ${MKL_C_FLAGS}"
  "-DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS} ${MKL_CXX_FLAGS}"
  -DCMAKE_INSTALL_RPATH:PATH=${CMAKE_INSTALL_RPATH}
  -DEIGEN3_INCLUDE_DIR:PATH=${EIGEN_INCLUDE_DIR}
  -Dglog_DIR:PATH=${Glog_DIR}
  -Dgflags_DIR:PATH=${gflags_DIR}
  -DSophus_DIR:PATH=${Sophus_DIR}
  -DTINYXML2_INCLUDE_DIRS:PATH=${TINYXML2_INCLUDE_DIRS}
  -DTINYXML2_LIBRARIES:FILEPATH=${TINYXML2_LIBRARIES}
  -DTINYXML2_INCLUDE_DIR:PATH=${TINYXML2_INCLUDE_DIR}
  -DTINYXML2_LIBRARY:FILEPATH=${TINYXML2_LIBRARY}
  -DSophus_INCLUDE_DIRS:PATH=${Sophus_INCLUDE_DIRS}
  -DOpenCV_DIR:PATH=${OpenCV_DIR}
  -DBUILD_APPLICATIONS:BOOL=OFF
  -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -Dtinyxml2_DIR:PATH=${tinyxml2_DIR}
  -DEXPORT_Calibu:BOOL=OFF
  -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}
  -DCMAKE_ANDROID_NDK:PATH=${CMAKE_ANDROID_NDK}
  -DCMAKE_ANDROID_ARCH_ABI:STRING=${CMAKE_ANDROID_ARCH_ABI}
  -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION:STRING=${CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION})


ExternalProject_Add(${EP_NAME}
  DEPENDS ${EP_REQUIRED_PROJECTS}
  GIT_REPOSITORY  ${EP_URL}
  GIT_TAG master
  UPDATE_DISCONNECTED 1
  SOURCE_DIR ${PROJECT_BINARY_DIR}/src/${EP_NAME}
  CMAKE_ARGS ${EP_CMAKE_ARGS}
  BINARY_DIR ${PROJECT_BINARY_DIR}/${EP_NAME}-build
  INSTALL_DIR ${PROJECT_BINARY_DIR}/install)

set(${EP_NAME}_DIR "${PROJECT_BINARY_DIR}/install/lib/cmake/${EP_NAME}" CACHE INTERNAL "")
