set(EP_URL "https://github.com/dcnieho/FreeGLUT")

cma_end_definition()

set(EP_CMAKE_ARGS
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
  -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
  -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
  -DFREEGLUT_BUILD_DEMOS:BOOL=OFF
  -DFREEGLUT_BUILD_SHARED_LIBS:BOOL=OFF
  -DINSTALL_PDB:BOOL=OFF
  -DFREEGLUT_REPLACE_GLUT:BOOL=OFF
  -DCMAKE_C_COMPILER_LAUNCHER:FILEPATH=${CMAKE_C_COMPILER_LAUNCHER}
  -DCMAKE_CXX_COMPILER_LAUNCHER:FILEPATH=${CMAKE_CXX_COMPILER_LAUNCHER})

ExternalProject_Add(${EP_NAME}
  GIT_REPOSITORY  ${EP_URL}
  GIT_TAG 9ea7d99574d0d3e8337bf5ca2eb1d564fdf991ea #git_master
  UPDATE_DISCONNECTED 1
  SOURCE_DIR ${PROJECT_BINARY_DIR}/src/${EP_NAME}
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -G ${CMAKE_GENERATOR} ${PROJECT_BINARY_DIR}/src/${EP_NAME}/freeglut/freeglut ${EP_CMAKE_ARGS}
  BINARY_DIR ${PROJECT_BINARY_DIR}/${EP_NAME}-build
  INSTALL_DIR ${PROJECT_BINARY_DIR}/${EP_NAME}-install)


set(${EP_NAME}_DIR "${PROJECT_BINARY_DIR}/${EP_NAME}-install/lib/cmake/${EP_NAME}" CACHE INTERNAL "")
